# Generated by Django 3.2.3 on 2021-05-26 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cursos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('duracion', models.CharField(max_length=100)),
                ('costo', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('direccion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiantes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('num_documento', models.IntegerField()),
                ('num_telefono', models.IntegerField()),
                ('correo', models.EmailField(max_length=254)),
                ('id_curso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrudEstudiantes.cursos')),
                ('id_direcciones', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CrudEstudiantes.direcciones')),
            ],
        ),
    ]
