# Generated by Django 3.2.3 on 2021-05-27 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudEstudiantes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cursos',
            old_name='id',
            new_name='cod',
        ),
        migrations.RenameField(
            model_name='direcciones',
            old_name='id',
            new_name='cod',
        ),
        migrations.RenameField(
            model_name='estudiantes',
            old_name='id',
            new_name='cod',
        ),
    ]
