# Generated by Django 3.2.3 on 2021-05-27 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudEstudiantes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='num_documento',
            field=models.IntegerField(max_length=100),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='num_telefono',
            field=models.IntegerField(max_length=100),
        ),
    ]
