# Generated by Django 3.2.3 on 2021-05-27 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudEstudiantes', '0002_auto_20210527_1656'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiantes',
            name='num_documento',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='num_telefono',
            field=models.BigIntegerField(),
        ),
    ]
