# Generated by Django 3.2.3 on 2021-05-27 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CrudEstudiantes', '0002_auto_20210527_2041'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estudiantes',
            old_name='id_curso',
            new_name='cod_curso',
        ),
        migrations.RenameField(
            model_name='estudiantes',
            old_name='id_direcciones',
            new_name='cod_direcciones',
        ),
    ]
