# Generated by Django 3.2.3 on 2021-05-27 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CrudEstudiantes', '0003_auto_20210527_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='fecha_fin',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='cursos',
            name='fecha_inicio',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='estudiantes',
            name='fecha_nacimiento',
            field=models.DateField(),
        ),
    ]
